### ISSUE TITLE
TraceableVoter seems to retain tags from inner service

### ISSUE THREAD

**Issue by kbond** [symfony/symfony#29550]
**Symfony version(s) affected**: 4.2.0

**Description**  
I have a voter that implements `ServiceSubscriberInterface`. When clearing the cache I get the following error:

```
[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]                                                                                         
  Service "debug.security.voter.App\Voter\MyVoter" must implement interface "Symfony\Contracts\Service\ServiceSubscriberInterface".
```

**How to reproduce**  
Create a auto-configured voter that implements `ServiceSubscriberInterface` and clear the cache in dev.

**Possible Solution**  
Not a solution but if I remove [this bit](https://github.com/symfony/symfony/blob/d069c264b34c0a087ef71016f2cd4a8903a41388/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Compiler/AddSecurityVotersPass.php#L58-L67) of code from `AddSecurityVoter`, it works as expected.

**Additional context**  
Possibly related to #29385?

Looks to have been introduced in #27914.

**Comment by chalasr** [comment]
Confirmed. 
The fact that `RegisterServiceSubscribersPass` runs after `DecoratorServicePass` makes it impossible to decorate a service implementing `ServiceSubscriberInterface` if the decorator does not implement it. 
I think the following change could fix it:

```diff
diff --git a/src/Symfony/Component/DependencyInjection/Compiler/PassConfig.php b/src/Symfony/Component/DependencyInjection/Compiler/PassConfig.php
index 31104fb..d547c3e 100644
--- a/src/Symfony/Component/DependencyInjection/Compiler/PassConfig.php
+++ b/src/Symfony/Component/DependencyInjection/Compiler/PassConfig.php
@@ -51,12 +51,12 @@ class PassConfig
         $this->optimizationPasses = array(array(
             new ResolveChildDefinitionsPass(),
             new ServiceLocatorTagPass(),
+            new RegisterServiceSubscribersPass(),
             new DecoratorServicePass(),
             new ResolveParameterPlaceHoldersPass(false),
             new ResolveFactoryClassPass(),
             new FactoryReturnTypePass($resolveClassPass),
             new CheckDefinitionValidityPass(),
-            new RegisterServiceSubscribersPass(),
             new ResolveNamedArgumentsPass(),
             new AutowireRequiredMethodsPass(),
             new ResolveBindingsPass(),
```

Could you please try it and confirm everything keeps working? 
Thanks

**Comment by kbond** [comment]
Thanks @chalasr - your fixed worked. I opened a PR
