### PR TITLE
[TwigBridge] fix BC break caused by using FormRenderer instead of TwigRenderer

### PR DESCRIPTION
**Pull request by dmaicher**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #24616, #25659
| License       | MIT
| Doc PR        | -

In https://github.com/symfony/symfony/commit/6ea71cb2ccc205294798d809e2ee295cfd9a0b5f#diff-5eb0532c96734f6e23428e921225b2f0R21 the `TwigRenderer` service was replaced with `FormRenderer`.

This caused 2 BC breaks:

- people that were injecting `twig.form.renderer` **and** coding against the interface `TwigRendererInterface` suddenly received an error because the new `FormRenderer` does not implement this interface.
- also retrieving the twig runtime for the old  FQCN is not working anymore and causes a `Twig_Error_Runtime` exception

This PR reverts the class change for the service `twig.form.renderer`. This should be safe to revert because the old `TwigRendererInterface` extends `FormRendererInterface` and `TwigRenderer` extends `FormRenderer`. So all people that adapted to the BC break and changed the expected interface/class should still be fine.

Additionally because some people already adjusted to the second BC break when retrieving the runtime (see for example https://github.com/sonata-project/SonataAdminBundle/issues/4758) we add the new non-deprecated `FormRenderer` as a runtime as well.

So both of these work on 3.4 then:

```php
$twig->getRuntime(TwigRenderer::class)
$twig->getRuntime(FormRenderer::class)
```

WDYT? Did I forget something?

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
> people that were injecting twig.form.renderer

when moving on 4.0, what will these people inject?

**Comment by dmaicher** [comment]
> when moving on 4.0, what will these people inject?

maybe a bit misleading what I wrote. That service `twig.form.renderer` still exists on 4.0 and there its the non-deprecated `FormRenderer` class (as `TwigRenderer` was removed).

So when upgrading to 4.0 its documented here as a BC break: https://github.com/symfony/symfony/blob/master/UPGRADE-4.0.md#twigbridge

**Comment by nicolas-grekas** [comment]
From what I understand, ppl using `twig.form.renderer` in 3.4 will get a deprecation for the class, so they will seek for removing this deprecation in 3.4, before moving to 4.0. I feel like there is a missing upgrade path, don't you ?

**Comment by dmaicher** [comment]
> From what I understand, ppl using `twig.form.renderer` in 3.4 will get a deprecation for the class, so they will seek for removing this deprecation in 3.4, before moving to 4.0

This is not correct for the current 3.4 as the service class was changed to `FormRenderer` together with deprecating it in one step (which is a BC break).

With my change people will indeed see a deprecation notice when using `twig.form.renderer` on 3.4.

**Comment by nicolas-grekas** [comment]
> you mean with the changes in this PR there is no upgrade path because of the deprecation notice

yes, that's what I meant

> this was the same for some other deprecated Symfony service classes or not?

if yes, we should do stricter reviews, this should not be the case.

In the end, shouldn't we live with this BC break and document it in UPGRADE files?
I don't have a better idea to fix the BC break :(

**Comment by dmaicher** [comment]
In the end I'm also fine with just allowing this BC break and document it. What do you think @Tobion ?

**Comment by Tobion** [comment]
If we change it back, more people will get deprecations without upgrade path. So to me it's better document the small bc break.

**Comment by dmaicher** [comment]
See https://github.com/symfony/symfony/pull/26570
