### PR TITLE
[Security] Decide IS_AUTHENTICATED_RECENTLY through the trust resolver

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 8.2
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | yes
| Issues        | -
| License       | MIT

Follow-up to #66014, which is merged, and independent of #66016. This answers the point raised there: time is a reasonable default but a poor sole signal, and an application should be able to weigh other risk factors, such as whether the IP address changed since the last authentication, a last-activity timer, or a recently confirmed second factor.

`AuthenticationTrustResolver::isAuthenticatedRecently()` is where that decision now lives, so overriding it replaces the whole strategy without touching the attribute it answers:

```php
class StepUpTrustResolver extends AuthenticationTrustResolver
{
    public function isAuthenticatedRecently(?TokenInterface $token = null): bool
    {
        return parent::isAuthenticatedRecently($token) && $this->sameClientAsAtLogin($token);
    }
}
```

### BC

The method is announced with `@method` on `AuthenticationTrustResolverInterface` rather than declared on it, so `DebugClassLoader` reports a custom resolver that does not implement it, and until the method joins the interface in 9.0 `AuthenticatedVoter` denies `IS_AUTHENTICATED_RECENTLY` for such a resolver rather than guessing. Failing closed is the right direction for an authorization attribute, and it keeps the voter free of a second copy of the strategy. Covered under `#[Group('legacy')]`.

The lifetime and the clock move from `AuthenticatedVoter` to `AuthenticationTrustResolver`, which is where the strategy now is; the voter takes only the trust resolver again. Both arguments were introduced in #66014 in this same stack and have never been released, so nothing is owed for the move. `security.recent_authentication_lifetime` is unchanged, it is simply wired to the trust resolver instead.

### Being full fledged stays an invariant of the attribute

The voter keeps checking `isFullFledged()` itself before consulting the strategy. That is not distrust of the resolver: it is that the relationship between the attributes belongs to the attribute, not to the strategy. `IS_AUTHENTICATED_RECENTLY` is strictly stronger than `IS_AUTHENTICATED_FULLY`, and a remember-me cookie is precisely not proof that the user still holds their credentials, so the easiest possible override (returning true from some risk heuristic) must not be able to grant sudo on one. A test pins it.

It is not over-restrictive either: `isFullFledged()` is itself a method of the trust resolver, so an application that redefines what full fledged means still has that respected. The default `isAuthenticatedRecently()` keeps its own guard as well, because it is public API that can be called on its own; an override does not need to repeat it.

### Deliberately unchanged

A last-activity timer is the one signal on that list that would be wrong to fold into the default. Refreshing the stamp on activity would make the attribute measure presence rather than possession of credentials, which is the opposite of what sudo mode is for. An application that genuinely wants that can express it in an override, which is exactly why this is an extension point rather than a config flag.

### CODE REVIEW

File: src/Symfony/Component/Security/Core/Authentication/AuthenticationTrustResolver.php [hunk 1]
```diff
@@ -35,4 +47,21 @@ public function isFullFledged(?TokenInterface $token = null): bool
...
+     * Time is the default signal, and deliberately the only one: an application that wants
+     * to weigh other risk factors, such as the IP address changing or a recent second-factor
+     * confirmation, overrides this method rather than the attribute it answers.
+     *
+     * An override does not have to repeat the isFullFledged() check that AuthenticatedVoter
+     * already enforces; it is kept here because this method is also callable on its own.
+     */
+    public function isAuthenticatedRecently(?TokenInterface $token = null): bool
+    {
+        if (!$this->isFullFledged($token) || !$token->hasAttribute(AuthenticatedVoter::AUTH_TIME_ATTRIBUTE)) {
```
Comment (stof) [inline src/Symfony/Component/Security/Core/Authentication/AuthenticationTrustResolver.php]: This should probably have an explicit handling of `$token` being `null`.

The default implementation of other methods of the class guarantees that `null` is not a full fledged token, but there is nothing guaranteeing that a child class preserves that behavior. We should return `false` in such case instead of trying to call a method on `null`.

File: src/Symfony/Component/Security/Core/Authorization/Voter/AuthenticatedVoter.php [hunk 2]
```diff
@@ -148,6 +143,17 @@ public function vote(TokenInterface $token, mixed $subject, array $attributes, ?
         return $result;
     }
 
+    private function isAuthenticatedRecently(TokenInterface $token): bool
+    {
+        if (!method_exists($this->authenticationTrustResolver, 'isAuthenticatedRecently')) {
+            trigger_deprecation('symfony/security-core', '8.2', 'Not implementing "%s::isAuthenticatedRecently()" is deprecated, the method will be added to the interface in 9.0; "IS_AUTHENTICATED_RECENTLY" is denied until then.', \get_class($this->authenticationTrustResolver));
```
Comment (stof) [inline src/Symfony/Component/Security/Core/Authorization/Voter/AuthenticatedVoter.php]: should this use `get_debug_type` as done elsewhere ? AFAIR, it differs when using anonymous classes.

File: src/Symfony/Component/Security/Core/Authentication/AuthenticationTrustResolver.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Security/Core/Authentication/AuthenticationTrustResolver.php]: Agreed, and done: the check now starts with `null === $token`.

You are right that the guarantee was coming from the wrong place. `isFullFledged()` keeping null out is a property of this implementation, not of the contract, and an override that returns true for a null token would have reached `hasAttribute()` on null and fataled. A test pins it with a subclass doing exactly that, and it errors without the guard.

File: src/Symfony/Component/Security/Core/Authorization/Voter/AuthenticatedVoter.php (hunk 2 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Security/Core/Authorization/Voter/AuthenticatedVoter.php]: Yes, switched to `get_debug_type()`.

It matters here in particular: the resolver that triggers this deprecation is one that has not implemented the new method, which in tests and in quick userland overrides is very often an anonymous class, and `get_class()` renders those as `class@anonymous%0/path/to/File.php:12$0`. The test builds the expected message the same way, so the two cannot drift.
