### ISSUE TITLE
[TwigBundle] release 5.4.45 not compatible with twig 3.29.0

### ISSUE THREAD

**Issue by pluk77** [symfony/symfony#66193]
### Symfony version(s) affected

5.4

### Description

After updating Twig to 3.29.0, the twig bundle produces the following errors when warming up the cache:

```11:21:30 CRITICAL  [php] Uncaught Error: Too few arguments to function Twig\TemplateWrapper::unwrap(), 0 passed in /srv/www/symfony/twig-bundle/CacheWarmer/TemplateCacheWarmer.php on line 56 and exactly 1 expected ["exception" => ArgumentCountError { …}]```

### How to reproduce

Have a symfony 5.4 project that requires twig/twig.
use composer to update, which will install twig/twig 3.29

### Possible Solution

The twig bundle can either change its dependencies and fix twig/twig to <3.29, or the missing argument can be added:

old: 
```$files[] = (new \ReflectionClass($template->unwrap()))->getFileName();```

new:
```$files[] = (new \ReflectionClass($template->unwrap($this->twig)))->getFileName();```

### Additional Context

This is the commit that broke compatibility:

https://github.com/twigphp/Twig/commit/c1fc112047bd2c8bf5c4f4d762e52e7f48ccc602

TwigBridge is also affected, but there the option was chosen to restrict rather than fix:

https://github.com/symfony/twig-bridge/commit/de12256cb9a0e4b501974fbb8e1a9412418c7472

**Comment by pluk77** [comment]
Tagging @nicolas-grekas as the one adding the fix to TwigBridge.

**Comment by derrabus** [comment]
I propose to "fix" this issue in Twig instead: twigphp/Twig#4936

**Comment by stof** [comment]
See also https://github.com/twigphp/Twig/issues/4935 for the similar discussion in the Twig repo

**Comment by alongosz** [comment]
Hey 👋 
Thanks for resolving it in Twig. This hit Ibexa DXP 4.6 too.

A friendly reminder that the `5.4` branch still caps `twig/twig` at `<3.29`, untagged so far:
- [symfony/symfony@003d08c8c82f](https://github.com/symfony/symfony/commit/003d08c8c82f)
- [symfony/symfony@7ec3eb09ec5e](https://github.com/symfony/symfony/commit/7ec3eb09ec5e)

It probably needs adjusting before the next 5.4.x tag :)

**Comment by stof** [comment]
an unreleased fixed has been merged in Twig 3.x

**Comment by pluk77** [comment]
Thank you all for the quick fix
