### ISSUE TITLE
[ObjectMapper] ObjectMapper::map calling constructor without any arguments

### ISSUE THREAD

**Issue by PeKowa** [symfony/symfony#61348]
### Symfony version(s) affected

7.3.2

### Description

There seems to be an issue introduced by [https://github.com/symfony/symfony/pull/61036](https://github.com/symfony/symfony/pull/61036). 

When calling map with a FQDN as target the mapping fails because the constructor is called without any arguments. Prior to the change the constructor was not called at all because `$ctorArguments` is empty.

The issue does not occur when property promotion is being used because:

```
if (!$parameter->isPromoted()) {
    continue;
}
```

does not lead to the filling of `$ctorArguments` being skipped.

### How to reproduce

```
<?php

namespace App;

class Foo {
    public string $bar;

    public function __construct(string $bar) {
        $this->bar = $bar;
    }
}
```
```
<?php

namespace App\Controller;

use App\Foo;
use stdClass;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\ObjectMapper\ObjectMapperInterface;

#[AsCommand(name: 'test')]
class TestCommand extends Command
{
    public function __construct(
        private readonly ObjectMapperInterface $mapper,
    ) {
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $object = new stdClass();
        $object->bar = 'bar';

        $foo = $this->mapper->map($object, Foo::class);

        return Command::SUCCESS;
    }
}
```
`Too few arguments to function App\Foo::__construct(), 0 passed in /var/www/html/vendor/symfony/object-mapper/ObjectMapper.php on line 159 and exactly 1 expected`

**Comment by elmehdi-elmais** [comment]
You can fix this by using *constructor property promotion* along with the `#[Map()]` attribute from `symfony/object-mapper`:

```php
use Symfony\Component\ObjectMapper\Attribute\Map;

class Foo {
    public function __construct(
        #[Map('bar')]
        public readonly string $bar
    ) {}
}

**Comment by rvanlaak** [comment]
The command from your reproducer does solely seem to be boilerplate code, that solely is wiring the object mapper.

What is the source, and what is the target you're trying to map? And using what command?

**Comment by frozenbrain** [comment]
@rvanlaak His reproducer is short but sufficient to reproduce the issue.

Here's an even shorter one, without most of the boilerplate:
```php
class Foo {
    public function __construct(string $bar) {
    }
}

$mapper = new ObjectMapper();
$output = $mapper->map(new stdClass(), Foo::class);

var_dump($output);
```

Now obviously this snippet doesn't do anything useful, but it worked in 7.3.1, whereas it produces an `ArgumentCountError` error in 7.3.2 (and 7.3.3). Before 7.3.2 the constructor call was skipped entirely, but the properties were still mapped correctly.

If this change in behavior was intended, then it would probably be a good idea to throw a more meaningful exception in case the target class has any non-promoted constructor arguments.

**Comment by rvanlaak** [comment]
Skipping a constructor on the instantiation of an object does sounds like an unwanted situation to me, so the fix of #61036 is correct.

Tried finding the reason of having the code snippet you're referring to, and can not find any trace nor can think of a reason why the object mapper should skip target constructor parameters when they aren't promoted. 

```php
if (!$parameter->isPromoted()) {
    continue;
}
```

So, wrote a test based on your input and made minor changes to the object mapper. PR #61785 should resolve this issue, @frozenbrain @PeKowa  can you verify that locally on your situation?

**Comment by frozenbrain** [comment]
Thanks! I tested your change locally and can confirm that non-promoted parameters now work as well, which is great for target classes with more complex constructors.

To provide some more context on how we stumbled across this, here's a rough outline of our situation:
```php
#[Map(target: TargetEntity::class)]
class SourceDto {
    public string $name;
}

class TargetEntity {
    public int $referenceId;
    public string $name;
    public ?string $description = null;

    public function __construct(int $referenceId, string $name)
    {
        $this->referenceId = $referenceId;
        $this->name = $name;
    }
}
```

We have a controller that maps a user-provided `SourceDto` (deserialized from the request body) to a `TargetEntity` that will later be persisted in a database. The constructor requires all non-nullable fields as parameters. The `referenceId` is a field that is required but not contained in the Dto, therefore we create the `TargetEntity` as follows:

```php
$entity = $mapper->map($sourceDto);
$entity->referenceId = 123; # Just as an example
```

While this _technically_ worked previously, I agree that _not_ calling the constructor if there is one is incorrect. This was the result of refactoring our entities from constructor-less Doctrine entities with inconsistent nullability generated by the Maker Bundle (which are, in my opinion, equally undesirable).

This unfortunately leads to a tricky situation: Can we still use the ObjectMapper if not all required constructor arguments are part of the source object? I couldn't find a simple way yet that isn't either overly verbose or feels like another hack to replace the old one (like adding the field to the Dto where it doesn't belong or leaving the property uninitialized by the constructor like before). Having a way to provide additional properties to the mapper would be helpful here, I think.

I feel like this goes beyond the scope of this issue though. If so, feel free to close this as completed, as I believe your new PR fixes the core of the issue that #61036 introduced. Still if you have any suggestions for a solution I may have overlooked, I'd appreciate your input.

**Comment by rvanlaak** [comment]
Possibly, when `name` isn't a hard requirement, constructing and mapping are performed the wrong way around? Forget Doctrine, forget ObjectMapper; the target object you're referring to seems to solely depend on `referenceId` in order to be "validly" constructed. In the next "write" you could apply the optional (null or undefined by default) fields like `name`. After construction an object has to be in a valid state, and the fact that Doctrine is used as persistence layer would be implementation detail.

Back to ObjectMapper; when not all data is available on `source` (read: there is no way ObjectMapper can retrieve `referenceId`) to validly construct `target`, we can not rely on ObjectMapper to instantiate the object. The ObjectMapper can be used after construction to write the other, publicly exposed values:

So instead of:

```php
$entity = $mapper->map($sourceDto, TargetEntity::class);
$entity->referenceId = 123;
```

the semantically more valid approach, by passing the instantiated object as target, to let ObjectMapper solely be responsible for the write:

```php
$referenceId = 123; // Retrieved from session or other state

$entity = new TargetEntity($referenceId);
$entity = $mapper->map($sourceDto, $entity);
```

In the situation where all fields are considered requirements on the target's constructor; then having a `with...` named constructor (PHPs recent `__clone` also is interesting) could help in getting the non-request related values into the source DTO. The construction of the source is outside of the scope of the ObjectMapper though...

```php
$sourceDto = $sourceDto->withReference(123); // Retrieved from session or other state

$entity = $mapper->map($sourceDto, TargetEntity::class);
```

**Comment by frozenbrain** [comment]
I believe that if I want to be consistent with my entities, I need to have all properties that are `NOT NULL` in the database to also be non-nullable in my classes. I would consider my entities "validly constructed", if all the required data is there, which is also very helpful for static code analysis.

Of course I could construct the object myself and only have the ObjectMapper fill the optional values after, but then what's the point if I have to map most fields manually anyways?

Leaving some properties uninitialized would certainly also be possible, but doing so just to satisfy the ObjectMapper feels wrong.

I could also create the entity manually and use the ObjectMapper only on updates or reads (entity -> DTO), but having two different ways to "map" also kind of misses the point in my opinion.

That only leaves me with adding the property to my DTO, which is what I'm currently doing as a workaround. This _technically_ works but the field is only there for that one specific time I need to actually construct a new entity (it never changes on updates and is never sent out to clients).

It's a shame, really, that such a seemingly small problem causes a pretty major road block. But then again this may just be beyond an "automatic" ObjectMapper and require manual programming, and maybe this just isn't a valid use case for it. I'd just really like to avoid using the ObjectMapper for some, but not all mapping tasks, because I can't pass an additional required constructor parameter that isn't in the source 😄 Currently there just doesn't seem to be a solution without drawbacks as far as I can tell.
