### ISSUE TITLE
Dependency Injection not more working for Validators

### ISSUE THREAD

**Issue by ThomasTr** [symfony/symfony#60611]
### Symfony version(s) affected

7.3.0

### Description

Trying to upgrade to Version 7.3.0 and get the following error: "Too few arguments to function App\Validator\ProductValidator::__construct(), 0 passed in Projects/app/vendor/symfony/validator/ContainerConstraintValidatorFactory.php on line 49 and exactly 1 expected"

### How to reproduce

My Constructor for my ProductValidator looks these:

```
    public function __construct(public EntityManagerInterface $entityManager)
    {
    }
```

The validator is called as assert via attributes in my DTO:

```
    #[AppAssert\Product]
    private array $productIds;
```

And validated here:
```
        /** @var T $dto */
        $dto        = $this->deserialize($this->extract($request), $type, $request);
        $violations = $this->validator->validate($dto);
```

### Additional Context

In previous version this has worked. Has anything changed here?

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by ThomasTr** [comment]
Had one #[\Attribute] too many in my validator service (also in the class that extends the ConstraintValidator). This does not seem to have been a problem in versions lower than 7.3, and has now led to this error when upgrading to 7.3.
