### ISSUE TITLE
[SecurityGuard] PostAuthenticationGuardToken does not implement getFirewallName()

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#38421]
**Symfony version(s) affected**: 5.2.0-beta1

**Description**  

I've upgraded a Symfony 5.1 application that uses a Guard authenticator to Symfony 5.2-beta1. The following deprecation is logged:

> User Deprecated: Since symfony/security-http 5.2: Method "Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken::getProviderKey()" has been deprecated, rename it to "getFirewallName()" instead.

I believe my application can't do much about it because the class in question is a Symfony class.

**How to reproduce**  
Use a guard authenticator.

**Possible Solution**  
Implement `getFirewallName()` on `PostAuthenticationGuardToken`.

**Additional context**  
The deprecation was introduced with #37942, but apparently the Guard component has not been updated accordingly. /cc @wouterj

**Comment by wouterj** [comment]
Based on https://github.com/symfony/symfony/issues/15207#issuecomment-674724120 , I decided to only update classes that were used by the new (yet still experimental) authenticator system. That's why Guard hasn't been updated (Guard is likely to be removed in 6.0 and the new authenticator system will be non-experimental in at least 5.4).

So indeed, we end up with deprecation that can't be fixed by the user (yet). What should we do here?

A) Remove the deprecation & re-introduce when the new system as is no longer experimental;
B) Update all internal tokens to use `getFirewallName()` to avoid the deprecation;
C) Leave the deprecation as-is.

**Comment by derrabus** [comment]
The application developer should be able to create a deprecation-free application. The error message that a developer currently receives is not helpful because it affects a class that is not under their control and that is also not flagged as deprecated (yet). This will just create unnecessary confusion, imho.

Since the Guard component has not been deprecated yet and the possible replacement is still experimental, I'd be in favor of silencing that deprecation. If the solution is as simple as creating an alias method on that token class, I'd go for it.

**Comment by derrabus** [comment]
PR: #38422
