### ISSUE TITLE
Symfony/Serializer Symfony2.8.19

### ISSUE THREAD

**Issue by Myystigri** [symfony/symfony#22522]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.19

When installing Symfony/Serializer ~3.2 with composer i get this issue 
![image](https://cloud.githubusercontent.com/assets/16547785/25388864/4293b1e6-29cf-11e7-9742-e3204e1a2a88.png)

It works fine with ~3.1

**Comment by stof** [comment]
installing the component at one version while using the fullstack repo at another version is not supported. This cannot work fine, as you would end up with multiple definitions of the classes, and you could be loading a mix of the 2.8 and 3.2 classes for the serializer component, causing weird issues.
The fact that it works in *some* cases is actually a bug in composer (related to some optimizations it applies).
