### PR TITLE
[SecurityGuard] Implement PostAuthenticationGuardToken::getFirewallName()

### LINKED ISSUE #38421: [SecurityGuard] PostAuthenticationGuardToken does not implement getFirewallName()
**Symfony version(s) affected**: 5.2.0-beta1

**Description**  

I've upgraded a Symfony 5.1 application that uses a Guard authenticator to Symfony 5.2-beta1. The following deprecation is logged:

> User Deprecated: Since symfony/security-http 5.2: Method "Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken::getProviderKey()" has been deprecated, rename it to "getFirewallName()" instead.

I believe my application can't do much about it because the class in question is a Symfony class.

**How to reproduce**  
Use a guard authenticator.

**Possible Solution**  
Implement `getFirewallName()` on `PostAuthenticationGuardToken`.

**Additional context**  
The deprecation was introduced with #37942, but apparently the Guard component has not been updated accordingly. /cc @wouterj

### PR DESCRIPTION
**Pull request by derrabus**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #38421
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Thank you @derrabus.
