### PR TITLE
[Console] Fix "regular expression is too large" when wrapping on wide terminals

### PR DESCRIPTION
**Pull request by HypeMC**
| Q             | A
| ------------- | ---
| Branch?       | 8.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | -
| License       | MIT

Fixes a bug caused by #63784:

> In OutputWrapper.php line 72:
>
> Warning: preg_replace(): Compilation failed: regular expression is too large at offset 245

The terminal width ends up in the `OutputWrapper` regex as a repetition count on a group, roughly `(?:tag|url|.){1,200}`. PCRE compiles a bounded repetition of a group by copying the group's bytecode once per repetition, and the group appears twice in the pattern. The compiled pattern hits PCRE's size limit at around 137 columns, so any wider terminal made `preg_replace()` fail. Since `preg_replace()` returns `null` on failure, the text being wrapped was also swallowed.

The fix makes the repetition apply to a single character instead of a group: every formatter tag and URL is first replaced with a single unused private-use codepoint, the text is wrapped with `.{1,width}`, and the codepoints are restored afterwards. A bounded repetition of a single character compiles to a counter of constant size, valid up to the quantifier limit of 65535. Each tag and each URL already counted as one repetition unit before, so the wrapped output is unchanged for widths that used to compile.

Descriptions now wrap at the real terminal width on any terminal.

### CODE REVIEW

File: src/Symfony/Component/Console/Descriptor/TextDescriptor.php [hunk 1]
```diff
@@ -33,6 +33,7 @@ class TextDescriptor extends Descriptor
 {
     private const MIN_DESCRIPTION_WIDTH = 20;
     private const FALLBACK_DESCRIPTION_INDENT = 6;
+    private const MAX_WRAP_WIDTH = 120;
```
Comment (HypeMC) [inline src/Symfony/Component/Console/Descriptor/TextDescriptor.php]: Same as `SymfonyStyle::MAX_LINE_LENGTH`

**Comment by nicolas-grekas** [comment]
Thanks @HypeMC for the quick catch and the precise diagnosis. I reworked the branch to remove the limitation instead of guarding against it, so wrapping keeps working on wide terminals rather than switching off above 120 columns.

The key fact is that PCRE only duplicates bounded repetitions of groups; a bounded repetition of a single character compiles to a counter of constant size, valid up to 65535. So `wrap()` now folds each tag and URL to a single unused private-use codepoint, wraps with `.{1,width}`, and restores them at the end. Each tag and each URL already counted as one repetition unit, so the semantics are unchanged.

What I checked:

- a differential fuzz over 23200 cases (tags, URLs, multibyte, tabs, CRLF, over-long words, both `allowCutUrls` modes) at widths 1 to 136 produces byte-for-byte the same output as the previous pattern;
- the full Console test suite passes;
- widths from 137 up to and beyond the quantifier limit now wrap instead of failing, and `preg_replace()` no longer returns `null`, which used to swallow the text being wrapped.

I flipped the new descriptor test accordingly: a 200-column terminal now asserts wrapped output, and `OutputWrapperTest` covers the two widths that used to fail. I also updated the description to match.

**Comment by HypeMC** [comment]
@nicolas-grekas Brilliant idea, I've tested it and it works perfectly. As always, big thanks!

**Comment by nicolas-grekas** [comment]
Thank you @HypeMC.
