### ISSUE TITLE
Error with dispatching messages for AMQP transport using Symfony Messenger

### ISSUE THREAD

**Issue by igordmed** [symfony/symfony#32088]
**Symfony version(s) affected**: 4.3.1

**Description**  
An error is being thrown when dispatching a message using the MessageBus from Symfony Messenger. Everything is properly configured since it was working with no problems with this in the previous 4.2.8 version of the component. The error began when I updated Symfony (with all dependencies) to 4.3.1.

The error is:

`Too few arguments to function Symfony\Component\Messenger\Transport\TransportFactory::createTra
  nsport(), 2 passed in /app/messaging-poc/var/cache/dev/Container7jXe42N/g
  etMessenger_Transport_AmqpService.php on line 18 and exactly 3 expected'`

The createTransport call from the cache getMessenger_Transport_AmqpService.php method which was generated from a Messenger service:

```
return $this->privates['messenger.transport.amqp'] = (new \Symfony\Component\Messenger\Transport\TransportFactory(new RewindableGenerator(function () {
    yield 0 => ($this->privates['messenger.transport.amqp.factory'] ?? $this->load('getMessenger_Transport_Amqp_FactoryService.php'));
}, 1)))->createTransport($this->getEnv('MESSENGER_TRANSPORT_DSN'), []);
```

**How to reproduce**  
So, I'm created a minimal Symfony application to use Symfony Messenger and try to send/receive AMQP messages.

So, inside `messenger.yaml` I have the following code (previously the dns value was directly placed on the amqp property):
````
framework:
    messenger:
        transports:
            amqp:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        routing:
            # Route your messages to the transports
            '*': amqp
````
The `.env` file has the DNS defined as `MESSENGER_TRANSPORT_DSN=amqp://test:test@127.0.0.1:5672/%2f/messages`;

Also, I created a symfony `Command` class to send AMQP messages through the CLI. The execute method is defined as follows:

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $output->writeln('Message sent: ' . $input->getArgument('message'));

        $this->messageBus->dispatch(new TextMessage($input->getArgument('message')),
            [new AmqpStamp('custom-routing-key', AMQP_NOPARAM, [])]);
    }

Any ideas on why this is happening? Inspecting the original createTransport method, it actually requires a `serializer` parameter, so maybe is something related to that... I've already tried to define default serializers in the  `messenger.yaml` file but nothing happened.

**Comment by xabbuh** [comment]
Can you publish an application that allows us to reproduce the issue?

**Comment by igordmed** [comment]
Sorry for the wait! Actually, I managed to fix the odd behavior but updating the messenger dependencies with `composer update messenger --with-dependencies`. Maybe some composer configuration didn't to it properly before, or it was a weird package conflict. Sorry for don't be able to track exactly what happened. 

I was trying to duplicate the application I'm working on to link it here but the dependencies are scattered through a couple of other packages. Sorry for the inconvenience and thank you for the quick reply.

**Comment by xabbuh** [comment]
Thank you for the feedback. Let's close here then.

**Comment by avaslev** [comment]
I have this error because surrounded the `DNS` with quotes (`"`) in `.env` like as `MESSENGER_ANY_DSN="doctrine://queue"`.
Removing `"` fix it for me.
