### ISSUE TITLE
[DoctrineBridge] ContainerAwareEventManager should be able to pass Entity with EventArgs

### ISSUE THREAD

**Issue by joffreyroy** [symfony/symfony#30475]
In Doctrine documentation, i found an interesting thing. Now events implement an Object in first parameter of listener. [https://www.doctrine-project.org/projects/doctrine-orm/en/latest/reference/events.html#entity-listeners](https://www.doctrine-project.org/projects/doctrine-orm/en/latest/reference/events.html#entity-listeners)

But when i want to use it, DoctrineBridge give me an error :
`Too few arguments to function App\EventListener\ProductListener::preUpdate(), 1 passed in /vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php on line 61 and exactly 2 expected`
I declare my listener like this :
`public function preUpdate( Product $product, PreUpdateEventArgs $event)  {   
//Custom logics  
}`

I go to /vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php on line 61 , and i see :
`$listener->$eventName($eventArgs);`

Can you update DoctrineBridge to be able to work with Doctrine >= 2.4 ?

**Comment by xabbuh** [comment]
The linked documentation is about entity listeners. Are they really dispatched through the event manager?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by joffreyroy** [comment]
> The linked documentation is about entity listeners. Are they really dispatched through the event manager?

Yes it is. I use break points with xdebug to show this behavior.

**Comment by xabbuh** [comment]
Can you show the code of your entity listener and how you did configure it?
